@HOST = http://localhost:8080/api

### @name create_instructor

POST {{HOST}}/instructors HTTP/1.1
Content-Type: application/json

{
	"email": "instructor2@gmail.com",
	"name": "example",
	"password": "example123"
}

### @name create_student

POST {{HOST}}/students HTTP/1.1
Content-Type: application/json

{
	"email": "student@gmail.com",
	"name": "student",
	"password": "example123"
}


### @name authentication

POST {{HOST}}/auth/instructor HTTP/1.1
Content-Type: application/json

{
	"email": "instructor2@gmail.com",
	"password": "example123"
}

### -------

POST {{HOST}}/auth/student HTTP/1.1
Content-Type: application/json

{
	"email": "student@gmail.com",
	"password": "example123"
}

### -------

POST {{HOST}}/auth/logout HTTP/1.1
Content-Type: application/json

### -------

GET {{HOST}}/auth/instructor/profile HTTP/1.1

### @name explore

GET {{HOST}}/explorer/instructors HTTP/1.1

### @name lessons


POST {{HOST}}/lessons HTTP/1.1
Content-Type: application/json

{
	"title": "Lesson 12",
	"description": "This is the first lesson",
	"instructorId": "639ec2e1-c181-44e5-9dc1-de0a79bf458c",
	"startAt":"2026-01-15T10:00:00Z"
}

###

GET {{HOST}}/lessons HTTP/1.1


###

PUT {{HOST}}/lessons/complete/01KDZVY0Z4F0B2SEE3GKPSFMDQ HTTP/1.1
Content-Type: application/json

### -------

GET {{HOST}}/gateway/stripe/connect HTTP/1.1

### @name payments

POST {{HOST}}/payments/link HTTP/1.1
Content-Type: application/json

{
	"lessonId": "01KE063AGWQFT62H3MTDPVYDVA"
}

###

POST {{HOST}}/payments/pix HTTP/1.1
Content-Type: application/json

{
	"lessonId": "01KE063AGWQFT62H3MTDPVYDVA"
}

###

POST {{HOST}}/instructors/refund HTTP/1.1
Content-Type: application/json

###
GET {{HOST}}/instructors/balance HTTP/1.1

###3ea98a45-0489-47f7-a87e-b4b76a06c12a